# Tell Nixpacks we are building a static frontend
[phases.build]
cmd = "npm install && npm run build"

# Static site served by nginx
[phases.start]
cmd = "nginx -g 'daemon off;'"

# Ensure correct Node version installed
[variables]
NODE_VERSION = "25"

# Static publish folder from Vite
[build]
assets = "/dist"